### ISSUE TITLE
Assertion failure when cloning a channel when the receiver no longer exists

### ISSUE THREAD

**Issue by jdm** [servo/ipc-channel#13]
```
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'assertion failed: mach_sys::mach_port_mod_refs(mach_task_self(), self.port,
                             MACH_PORT_RIGHT_SEND, 1) == KERN_SUCCESS', /Users/jdm/.cargo/git/checkouts/ipc-channel-d95a23d1f1577bfc/master/platform/macos/mod.rs:292
* thread #6: tid = 0x26ded7, 0x000000010297fe90 servo`rust_panic, stop reason = breakpoint 1.1
  * frame #0: 0x000000010297fe90 servo`rust_panic
    frame #1: 0x000000010296e792 servo`sys_common::unwind::begin_unwind_inner::h1e338bc64cf56d9dr8r + 466
    frame #2: 0x0000000102606728 servo`ipc_channel::sys_common::unwind::begin_unwind<&str>(msg=(data_ptr = "assertion failed: mach_sys::mach_port_mod_refs(mach_task_self(), self.port,\n                             MACH_PORT_RIGHT_SEND, 1) == KERN_SUCCESS", length = 145), file_line=0x0000000104113d00) + 120 at mod.rs:214
    frame #3: 0x0000000102605cff servo`ipc_channel::platform::macos::MachSender.Clone::clone(self=0x0000000125a12790) + 143 at <std macros>:3
    frame #4: 0x0000000100fd22c5 servo`script::ipc::IpcSender<T>.Clone::clone(self=0x0000000125a12790) + 21 at ipc.rs:122
    frame #5: 0x0000000100fd08a3 servo`fnfn + 787 at script_task.rs:513
    frame #6: 0x0000000100fd04f8 servo`fnfn + 104 at task.rs:52
    frame #7: 0x0000000100fd0448 servo`script::boxed::F.FnBox<A>::call_box(self=0x0000000115c43280, args=<unavailable>) + 104 at boxed.rs:516
    frame #8: 0x000000010079511c servo`script::boxed::Box<FnBox<A, Output = R>+ Send + 'a>.FnOnce<A>::call_once(self=Box<FnBox<()>> at 0x0000000125a12bc0, args=<unavailable>) + 60 at boxed.rs:532
    frame #9: 0x0000000100794cee servo`fnfn + 78 at mod.rs:280
    frame #10: 0x0000000100794c9a servo`script::sys_common::unwind::try::try_fn<closure>(opt_closure=0x0000000125a12cf0) + 58 at mod.rs:146
    frame #11: 0x000000010297fe89 servo`__rust_try + 9
    frame #12: 0x000000010297d32f servo`sys_common::unwind::try::inner_try::hc13d8e198528cd0fZ4r + 111
    frame #13: 0x0000000100794c04 servo`script::sys_common::unwind::try<closure>(f=closure at 0x0000000125a12d08) + 100 at mod.rs:116
    frame #14: 0x0000000100794a7c servo`fnfn + 412 at mod.rs:280
    frame #15: 0x000000010079539d servo`script::boxed::F.FnBox<A>::call_box(self=0x0000000115c24440, args=<unavailable>) + 77 at boxed.rs:516
    frame #16: 0x0000000102981f6e servo`sys::thread::_$LT$impl$GT$::new::thread_start::h906ddce3a93d4852ksw + 142
    frame #17: 0x00007fff982c6899 libsystem_pthread.dylib`_pthread_body + 138
    frame #18: 0x00007fff982c672a libsystem_pthread.dylib`_pthread_start + 137
    frame #19: 0x00007fff982cafc9 libsystem_pthread.dylib`thread_start + 13
```

**Comment by glyn** [comment]
@jdm Does this still occur? I wonder if it was fixed by https://github.com/servo/ipc-channel/commit/09e2153d2db2159f23997eaad289b72a349544cd.

**Comment by jdm** [comment]
Agreed. This program does not panic:
```rust
fn main() {
    let (tx, rx) = ipc_channel::ipc::channel::<u32>().unwrap();
    drop(rx);
    let tx2 = tx.clone();
}
```
