### ISSUE TITLE
Crashes with "Bogus destination port" on macOS Mojave

### ISSUE THREAD

**Issue by ebkalderon** [servo/ipc-channel#248]
## Environment

* macOS Mojave 10.14.6 (18G1012)
* `rustc 1.34.1 (fc50f328b 2019-04-24)`
* `cargo 1.34.0 (6789d8a0a 2019-04-01)`
* `ipc-channel 0.12.2`

## Minimal verifiable example

Given this basic program:

```rust
fn main() {
    let (tx, rx) = ipc_channel::ipc::channel().unwrap();

    let pid = unsafe { libc::fork() };
    if pid == 0 {
        tx.send(123).unwrap();
        std::process::exit(0);
    } else {
        rx.recv().unwrap();
    }
}
```

I receive the following output with `cargo run`:

```
   Compiling foo v0.1.0 (/Users/eyalkalderon/Documents/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 2.27s
     Running `target/debug/foo`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: NotFound, error: StringError("Bogus destination port.") })', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidName', src/libcore/result.rs:997:5
stack backtrace:
   0:        0x107dcf1e3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hc4fae2e3c413d5b3
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:        0x107dcb602 - std::sys_common::backtrace::_print::h052936d888769c81
                               at src/libstd/sys_common/backtrace.rs:70
   2:        0x107dce246 - std::panicking::default_hook::{{closure}}::hf45b075b1f6a663f
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:        0x107dcdf51 - std::panicking::default_hook::h710fd6cdb9bcc1f7
                               at src/libstd/panicking.rs:215
   4:        0x107dce95f - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::hd305e3bc1f54d236
                               at src/libstd/panicking.rs:478
   5:        0x107dce48c - std::panicking::continue_panic_fmt::hedd2787bab78c9eb
                               at src/libstd/panicking.rs:385
   6:        0x107dce378 - std::panicking::try::do_call::h20c95c457c762d5f
                               at src/libstd/panicking.rs:312
   7:        0x107de20b1 - <T as core::any::Any>::type_id::h7499d8303120591e
                               at src/libcore/panicking.rs:85
   8:        0x107dbdf2e - alloc::raw_vec::alloc_guard::h3f29f6d9cb741ac9
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/macros.rs:17
   9:        0x107dbd45f - alloc::raw_vec::alloc_guard::h3f29f6d9cb741ac9
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/result.rs:798
  10:        0x107dac3cb - serde::ser::impls::<impl serde::ser::Serialize for i32>::serialize::hfe18a04d8589f845
                               at /Users/eyalkalderon/.cargo/registry/src/github.com-1ecc6299db9ec823/ipc-channel-0.12.2/src/platform/macos/mod.rs:133
  11:        0x107da4514 - core::ptr::real_drop_in_place::h6923e26e0ffb7639
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/ptr.rs:193
  12:        0x107da4664 - core::ptr::real_drop_in_place::h88d1a621349bca4c
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/ptr.rs:193
  13:        0x107daacc5 - foo::main::hd59dd3ffb040f0b8
                               at src/main.rs:30
  14:        0x107da1371 - std::rt::lang_start::{{closure}}::ha8c325c9f27bf796
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
  15:        0x107dce2f7 - std::panicking::try::do_call::h20c95c457c762d5f
                               at src/libstd/rt.rs:49
                               at src/libstd/panicking.rs:297
  16:        0x107dd05fe - panic_unwind::dwarf::eh::read_encoded_pointer::h19627c4bf27eeb46
                               at src/libpanic_unwind/lib.rs:87
  17:        0x107dced1d - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::hd305e3bc1f54d236
                               at src/libstd/panicking.rs:276
                               at src/libstd/panic.rs:388
                               at src/libstd/rt.rs:48
  18:        0x107da1351 - std::rt::lang_start::h5cc9c34c93fe629a
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
  19:        0x107daad81 - foo::main::hd59dd3ffb040f0b8
thread panicked while panicking. aborting.
```

This program behaves as expected on Linux, but reliably crashes with the error message above on macOS.

**Comment by ebkalderon** [comment]
By contrast, `std::os::unix::net::UnixStream` works just fine on macOS.

```rust
use std::io::{Read, Write};
use std::os::unix::net::UnixStream;

fn main() {
    let (mut tx, mut rx) = UnixStream::pair().unwrap();

    let pid = unsafe { libc::fork() };
    if pid == 0 {
        drop(rx);
        write!(&mut tx, "hello").unwrap();
        std::process::exit(0);
    } else {
        drop(tx);
        let mut buf = String::new();
        rx.read_to_string(&mut buf).unwrap();
        println!("received {}", buf);
    }
}
```

The program above prints the line `hello` to standard output, as expected.

**Comment by jdm** [comment]
You need to use IpcOneShotServer like [this unit test](https://github.com/servo/ipc-channel/blob/master/src/test.rs#L197-L216).

**Comment by ebkalderon** [comment]
@jdm Thanks for the helpful link! Should I update my Linux code to do the same? And why does the code sample behave as expected on Linux and not on macOS?

**Comment by jdm** [comment]
The underlying platform APIs provide different guarantees, I guess? The IpcOneShotServer is the only supported way of actually bootstrapping the inter-process communication mechanism in ipc-channel.

**Comment by ebkalderon** [comment]
I see. I didn't realize that was how the library was intended to be used, just by reading the documentation. Thanks a lot for the explanation! I think this issue can be closed, in that case, since this appears to be the expected behavior.
